### PR TITLE
WIP: Smesh 9.6.0

### PR DESCRIPTION
**Pull request by frmdstryr**
Updates for pyocct 7.5.2 and smesh 9.6.0 and to generate using pyOCCT_binder.

## Description

Main changes are:
- Changes to the binder to generate the bindings in the same way as pyOCCT
- Adds omniorb dependency that is needed for smesh 9.6
- A major hack of a header to import `netgen::OCCGeometry` and workaround relative imports. 

- Requires pyOCCT headers and src (currently in a relative path), does it make sense to include these with the pyocct package?

## Motivation and Context
Updates to latest and uses the binder so hopefully updating future version will be easier...

## How Has This Been Tested?
I ran the binder and compiled in a locally on linux created conda env then ran the examples. It is still WIP as I haven't tested building with conda yet.

## Screenshots (if appropriate):
image

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by trelau** [comment]
Nice! Regarding this point:

`Requires pyOCCT headers and src (currently in a relative path), does it make sense to include these with the pyocct package?`

In the beginning, SMESH was a module of pyOCCT (e.g., from OCCT.NETGENPlugin import *). The two projects seemed different enough (wrt use case, personas, etc.) to break them apart, plus I thought it'd make the projects cleaner. I think it's still up for debate if that is the right approach.

I can see how the dependencies make it complicated to manage. Can we make OCCT (or pyOCCT?) like a sumbmodule and manage the external dependencies/files that way? Sort of like how SMESH preps the files to build, pySMESH does that same (using CMake? or a script?).

**Comment by frmdstryr** [comment]
> I think it's still up for debate if that is the right approach.

Yea, I'm sort of torn on what's best here. One thing that Is nice about it split is that it doesn't take like 2 hours to compile.

> Can we make OCCT (or pyOCCT?) like a sumbmodule and manage the external dependencies/files that way? 

I didn't think about doing it that way but I think that would work the best.

**Comment by trelau** [comment]
iirc, the LMZA issue on windows i think comes from attempting to find_package VTK. I believe I had to explicitly call out the components like so https://github.com/trelau/SMESH/blob/fd120103d58fd0af046af8386436435d4abdee22/CMakeLists.txt#L71

**Comment by trelau** [comment]
this might be a stretch, but i wonder if the "double free" error on linux might be related to this? https://github.com/trelau/SMESH/issues/37 (it's an OSX issue but i wonder if related)

**Comment by frmdstryr** [comment]
Regarding the double free, In the current sources on master there's a `Deleter<T>` on several classes, I'm not sure how those were determined? ~~I think where the destructor is virtual?~~ Edit: This is incorrect.

**Comment by trelau** [comment]
This documentation from pyOCCT might provide some insight https://pyocct.readthedocs.io/en/latest/dev.html#non-public-destructors. Also, this doc and design decision was done early on when i was just learning, so if you spot anything strange, nothing is set in stone.

**Comment by trelau** [comment]
For specifying VTK components, you might need to call them out when linking (just referencing SMESH since i remember running into some of these issues) https://github.com/trelau/SMESH/blob/fd120103d58fd0af046af8386436435d4abdee22/cmake/SMESH/CMakeLists.txt#L114

**Comment by trelau** [comment]
and i think i had to add these lines to fix some issues i was having with pyOCCT where the python environments were not being found correctly https://github.com/trelau/pyOCCT/blob/42e90a8b19a323acfe8b83fe27a2ccf5aac748e5/ci/conda/build.sh#L21-L23

**Comment by trelau** [comment]
This may have also been part of getting the right python version found https://github.com/trelau/pyOCCT/blob/42e90a8b19a323acfe8b83fe27a2ccf5aac748e5/CMakeLists.txt#L67-L69

**Comment by trelau** [comment]
Looks like latest windows failure is maybe missing a link to a dependent library? https://github.com/trelau/pySMESH/pull/1/checks?check_run_id=3510802189#step:8:573

in general, i would expect the build process and linking to be a hybrid of the pyOCCT (for python bindings) process and SMESH (for the SMESH side of things). That is, the conda process and CMake files might share similar aspects. I wouldn't expect to have to do things very different like the omnithread and including windows.h stuff? That is, I would expect pyOCCT and SMESH to have already handled most of the dependency issues, and pySMESH is just adding python bindings so ideally there is few new complications. if that isn't the case, then perhaps that's an indicator something is wrong at a deeper level?

**Comment by trelau** [comment]
as a side note perhaps for future, anything we can use to automatically detect what needs `reference_internal` and/or `keep_alive`? even a (reliable) heuristic?

**Comment by frmdstryr** [comment]
> as a side note perhaps for future, anything we can use to automatically detect what needs reference_internal and/or keep_alive? even a (reliable) heuristic?

The only way to determine reference internal is if it returns an internal member or something it "owns". Idk if it's possible to know this without also having & parsing the source. Perhaps some name matching could be done. 

SMESH should be using smart pointers... all the keep alives are a workaround. I didn't get through everything yesterday so there's probably some I missed. There's also some that require keep alive for multiple arguments, idk if pybind supports that.  Not entirely sure if it's done correctly but some crashes I had went away by adding these.

Another issue is the SMDS iterators currently crash when using more/next, haven't figured out how to fix that yet.

**Comment by trelau** [comment]
fyi there is a new Salome 9.7 out that has  few fixes and enhancements that might be relevant https://github.com/trelau/SMESH/issues/50

**Comment by trelau** [comment]
working on updating SMESH to 9.7.0 here. everything seems ok except for a strange linux error https://github.com/trelau/SMESH/pull/51

**Comment by frmdstryr** [comment]
Well, this no longer works. Some linux builds for smesh 9.7 are in my personal repo if anyone is interested.

**Pull request closed without merging**
